CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(255) NOT NULL,
  email varchar(255) NOT NULL UNIQUE, role varchar(32) NOT NULL, active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE case_types (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code varchar(64) NOT NULL UNIQUE, name varchar(255) NOT NULL, active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE case_statuses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code varchar(64) NOT NULL UNIQUE, name varchar(255) NOT NULL, category varchar(32) NOT NULL, active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE cases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_number varchar(32) NOT NULL UNIQUE, applicant_id uuid NOT NULL REFERENCES applicants(id), case_type_id uuid NOT NULL REFERENCES case_types(id), current_status_id uuid NOT NULL REFERENCES case_statuses(id), created_by_id uuid NOT NULL REFERENCES users(id), opened_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE case_status_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid NOT NULL REFERENCES cases(id), from_status_id uuid NULL REFERENCES case_statuses(id), to_status_id uuid NOT NULL REFERENCES case_statuses(id), changed_by_id uuid NOT NULL REFERENCES users(id), reason text NOT NULL, changed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE case_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid NOT NULL REFERENCES cases(id), user_id uuid NOT NULL REFERENCES users(id), assigned_by_id uuid NOT NULL REFERENCES users(id), assigned_at timestamptz NOT NULL DEFAULT now(), unassigned_at timestamptz NULL);
CREATE UNIQUE INDEX case_assignments_one_active ON case_assignments(case_id) WHERE unassigned_at IS NULL;
CREATE TABLE timeline (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid NOT NULL REFERENCES cases(id), actor_id uuid NULL REFERENCES users(id), event_type varchar(64) NOT NULL, subject_type varchar(64) NOT NULL, subject_id uuid NULL, payload jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
INSERT INTO case_types (code,name,sort_order) VALUES ('VISA_APPLICATION','Visa Application',1),('VISA_EXTENSION','Visa Extension',2),('WORK_PERMIT','Work Permit',3),('WORK_PERMIT_RENEWAL','Work Permit Renewal',4),('NINETY_DAY_REPORT','90-Day Report',5),('RE_ENTRY_PERMIT','Re-Entry Permit',6),('PASSPORT_RENEWAL_SUPPORT','Passport Renewal Support',7),('OTHER','Other',8);
INSERT INTO case_statuses (code,name,category,sort_order) VALUES ('DRAFT','Draft','ACTIVE',1),('WAITING_DOCUMENTS','Waiting Documents','ACTIVE',2),('DOCUMENTS_COMPLETE','Documents Complete','ACTIVE',3),('PROCESSING','Processing','ACTIVE',4),('WAITING_GOVERNMENT_APPROVAL','Waiting Government Approval','ACTIVE',5),('COMPLETED','Completed','TERMINAL',6),('ON_HOLD','On Hold','PAUSED',7),('CANCELLED','Cancelled','TERMINAL',8),('REJECTED','Rejected','TERMINAL',9);
