"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { apiCall, Contact } from "../../lib/api";
import { dueLabel, dueState } from "../../lib/format";
import { AppShell, useCurrentUser, useDateFormat, useTimeZone } from "../components/app-shell";
import { RowMenu } from "../components/row-menu";
import "../app-pages.css";

function ContactsContent() {
  const params = useSearchParams(); const user = useCurrentUser(); const showDate = useDateFormat(); const timeZone = useTimeZone();
  const [contacts, setContacts] = useState<Contact[]>([]); const [search, setSearch] = useState(""); const [editing, setEditing] = useState<Contact | "new" | null>(params.get("new") === "1" ? "new" : null); const [deleting, setDeleting] = useState<Contact | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = async () => setContacts(await apiCall<Contact[]>("/contacts")); useEffect(() => { const timer = window.setTimeout(() => void load().catch((reason) => setError(reason instanceof Error ? reason.message : "Contacts failed")), 0); return () => window.clearTimeout(timer); }, []);
  const filtered = useMemo(() => contacts.filter((item) => `${item.name} ${item.email ?? ""} ${item.passportNumber ?? ""}`.toLowerCase().includes(search.toLowerCase())), [contacts, search]);
  const save = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const form = new FormData(event.currentTarget); setSaving(true); void apiCall(editing === "new" ? "/contacts" : `/contacts/${editing.id}`, { method: editing === "new" ? "POST" : "PATCH", body: JSON.stringify({ name: form.get("name"), email: form.get("email") || undefined, phone: form.get("phone") || undefined, notes: form.get("notes") || undefined }) }).then(async () => { setEditing(null); await load(); }).catch((reason) => setError(reason instanceof Error && reason.message === "CONTACT_IN_USE" ? "This contact is linked to an active Project." : reason instanceof Error ? reason.message : "Save failed")).finally(() => setSaving(false)); };
  const remove = () => { if (!deleting) return; setSaving(true); void apiCall(`/contacts/${deleting.id}`, { method: "DELETE", body: JSON.stringify({ deletedById: user.id }) }).then(async () => { setDeleting(null); await load(); }).catch((reason) => setError(reason instanceof Error && reason.message === "CONTACT_IN_USE" ? "This contact cannot be deleted because it is linked to an active Project." : reason instanceof Error ? reason.message : "Delete failed")).finally(() => setSaving(false)); };
  return <><header className="page-header"><div><p className="eyebrow">CONTACTS</p><h1>Contacts</h1><p>Manage personal, passport and contact details.</p></div><button className="btn primary" onClick={() => setEditing("new")}>+ New Contact</button></header>{error && <p className="error">{error}</p>}<div className="page-toolbar"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search contacts…" aria-label="Search contacts" /></div><p className="result-count" aria-live="polite">{`${filtered.length} of ${contacts.length} contact${contacts.length === 1 ? "" : "s"}`}</p><section className="data-panel table-scroll"><table className="data-table"><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Passport</th><th>Expiry</th><th>Actions</th></tr></thead><tbody>{filtered.map((contact) => <tr key={contact.id}><td>{contact.name}</td><td>{contact.email || "—"}</td><td>{contact.phone || "—"}</td><td>{contact.passportNumber || "—"}</td><td className="due-cell" data-due={dueState(contact.dateOfExpiry, timeZone)}>{showDate(contact.dateOfExpiry)}{dueLabel(contact.dateOfExpiry, timeZone) && <small>{dueLabel(contact.dateOfExpiry, timeZone)}</small>}</td><td><RowMenu label={`Actions for ${contact.name}`} items={[{ label: "Delete Contact", tone: "danger", onSelect: () => setDeleting(contact) }]}><button className="btn" onClick={() => setEditing(contact)}>Edit</button></RowMenu></td></tr>)}</tbody></table>{!filtered.length && <p className="empty-panel">No contacts found.</p>}</section>{editing && <div className="dialog-backdrop" role="dialog" aria-modal="true"><form className="dialog-card" onSubmit={save}><h2>{editing === "new" ? "New Contact" : "Edit Contact"}</h2><div className="form-grid"><label className="field full">Name<input name="name" required autoFocus defaultValue={editing === "new" ? "" : editing.name} /></label><label className="field">Email<input name="email" type="email" defaultValue={editing === "new" ? "" : editing.email ?? ""} /></label><label className="field">Phone<input name="phone" defaultValue={editing === "new" ? "" : editing.phone ?? ""} /></label><label className="field full">Notes<textarea name="notes" defaultValue={editing === "new" ? "" : editing.notes ?? ""} /></label></div><div className="dialog-actions"><button type="button" className="btn" onClick={() => setEditing(null)}>Cancel</button><button className="btn primary" disabled={saving}>Save</button></div></form></div>}{deleting && <div className="dialog-backdrop"><div className="dialog-card"><h2>Delete {deleting.name}?</h2><div className="dialog-actions"><button className="btn" onClick={() => setDeleting(null)}>Cancel</button><button className="btn danger" onClick={remove} disabled={saving}>Delete</button></div></div></div>}</>;
}
export default function ContactsPage() { return <AppShell><ContactsContent /></AppShell>; }
