"use client";

import { useSearchParams } from "next/navigation";
import { FormEvent, Suspense, useEffect, useMemo, useState } from "react";
import { apiCall, Company } from "../../lib/api";
import { AppShell } from "../components/app-shell";
import "../app-pages.css";

const companyName = (company: Company) => company.legalNameEn || company.legalNameTh || "Unnamed";

function CompaniesContent() {
  const params = useSearchParams();
  const [companies, setCompanies] = useState<Company[]>([]); const [search, setSearch] = useState(""); const [editing, setEditing] = useState<Company | "new" | null>(params.get("new") === "1" ? "new" : null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const filtered = useMemo(() => companies.filter((company) => `${companyName(company)} ${company.registrationNumber ?? ""}`.toLowerCase().includes(search.toLowerCase())), [companies, search]);
  const load = async () => setCompanies(await apiCall<Company[]>("/companies")); useEffect(() => { const timer = window.setTimeout(() => void load().catch((reason) => setError(reason instanceof Error ? reason.message : "Companies failed")), 0); return () => window.clearTimeout(timer); }, []);
  const save = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const form = new FormData(event.currentTarget); const body = { legalNameEn: form.get("legalNameEn") || undefined, legalNameTh: form.get("legalNameTh") || undefined, registrationNumber: form.get("registrationNumber") || undefined, registeredAddress: form.get("registeredAddress") || undefined, phone: form.get("phone") || undefined }; setSaving(true); void apiCall(editing === "new" ? "/companies" : `/companies/${editing.id}`, { method: editing === "new" ? "POST" : "PATCH", body: JSON.stringify(body) }).then(async () => { setEditing(null); await load(); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Save failed")).finally(() => setSaving(false)); };
  return <><header className="page-header"><div><p className="eyebrow">COMPANIES</p><h1>Companies</h1><p>Company details used by Projects and Form Data.</p></div><button className="btn primary" onClick={() => setEditing("new")}>+ New Company</button></header>{error && <p className="error">{error}</p>}<div className="page-toolbar"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search companies…" aria-label="Search companies" /></div><p className="result-count" aria-live="polite">{`${filtered.length} of ${companies.length} compan${companies.length === 1 ? "y" : "ies"}`}</p><section className="data-panel table-scroll">{filtered.length === 0 ? <p className="empty-panel">{companies.length === 0 ? "No companies yet." : "No companies match this search."}</p> : <table className="data-table"><thead><tr><th>Company</th><th>Registration</th><th>Phone</th><th>Address</th><th>Actions</th></tr></thead><tbody>{filtered.map((company) => <tr key={company.id}><td>{companyName(company)}</td><td>{company.registrationNumber || "—"}</td><td>{company.phone || "—"}</td><td>{company.registeredAddress || "—"}</td><td><button className="btn" onClick={() => setEditing(company)}>Edit</button></td></tr>)}</tbody></table>}</section>{editing && <div className="dialog-backdrop"><form className="dialog-card" onSubmit={save}><h2>{editing === "new" ? "New Company" : "Edit Company"}</h2><div className="form-grid"><label className="field">Legal name (English)<input name="legalNameEn" defaultValue={editing === "new" ? "" : editing.legalNameEn ?? ""} /></label><label className="field">Legal name (Thai)<input name="legalNameTh" defaultValue={editing === "new" ? "" : editing.legalNameTh ?? ""} /></label><label className="field">Registration number<input name="registrationNumber" defaultValue={editing === "new" ? "" : editing.registrationNumber ?? ""} /></label><label className="field">Phone<input name="phone" defaultValue={editing === "new" ? "" : editing.phone ?? ""} /></label><label className="field full">Registered address<textarea name="registeredAddress" defaultValue={editing === "new" ? "" : editing.registeredAddress ?? ""} /></label></div><div className="dialog-actions"><button type="button" className="btn" onClick={() => setEditing(null)}>Cancel</button><button className="btn primary" disabled={saving}>Save</button></div></form></div>}</>;
}
export default function CompaniesPage() { return <AppShell><Suspense fallback={<p>Loading…</p>}><CompaniesContent /></Suspense></AppShell>; }
